<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sdk\Sdk.csproj" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Serto.Connectors</PackageId>
    <Version>1.0.3</Version>
    <Authors>Craytech</Authors>
    <Company>Craytech</Company>
    <Description>Core connectors for Serto, providing simplified HTTP and SQL access.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/neweyc/integration-platform</PackageProjectUrl>
    <RepositoryUrl>https://github.com/neweyc/integration-platform</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>integration;automation;workflow;connectors;http;sql</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
